name: Test Coverage
on: [push]
jobs:
  build-push-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Generate coverage report
        run: |
          yarn install
          yarn test
      - name: Upload coverage
        if: success()
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
